### ISSUE TITLE
Objects

### ISSUE THREAD

**Issue by katiihnat** [Kandroodi/IberianSaints#23]
Current location can just be a text box (no drop-down menu) - because this is not something we want to put on the map ultimately, it doesn't need to be saved as a special 'site' with coordinates.

**Comment by Kandroodi** [comment]
The current location field is a drop-down menu because:
1) preventing entering the same information multiple times for different objects.
2) be sure that the same information is similar in the whole database. Preventing misspelling and multiple variants for the same entry.
3) be sure that in the search function we can retrieve all data correctly.
So, we need to solve this issue in another way.

**Comment by Kandroodi** [comment]
It is done.
